// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: define/trade/open_state.proto

package trade

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenState int32

const (
	OpenState_OpenStateUnknown OpenState = 0
	OpenState_Open             OpenState = 1
	OpenState_Close            OpenState = 2
)

// Enum value maps for OpenState.
var (
	OpenState_name = map[int32]string{
		0: "OpenStateUnknown",
		1: "Open",
		2: "Close",
	}
	OpenState_value = map[string]int32{
		"OpenStateUnknown": 0,
		"Open":             1,
		"Close":            2,
	}
)

func (x OpenState) Enum() *OpenState {
	p := new(OpenState)
	*p = x
	return p
}

func (x OpenState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenState) Descriptor() protoreflect.EnumDescriptor {
	return file_define_trade_open_state_proto_enumTypes[0].Descriptor()
}

func (OpenState) Type() protoreflect.EnumType {
	return &file_define_trade_open_state_proto_enumTypes[0]
}

func (x OpenState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenState.Descriptor instead.
func (OpenState) EnumDescriptor() ([]byte, []int) {
	return file_define_trade_open_state_proto_rawDescGZIP(), []int{0}
}

var File_define_trade_open_state_proto protoreflect.FileDescriptor

var file_define_trade_open_state_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2f, 0x6f,
	0x70, 0x65, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2a, 0x36, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x70, 0x65,
	0x6e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x10, 0x02, 0x42, 0x8e,
	0x01, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x65, 0x42, 0x0e, 0x4f, 0x70,
	0x65, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x7a, 0x6c, 0x2d, 0x68,
	0x65, 0x72, 0x65, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x2d, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x2d, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x65, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x3b, 0x74, 0x72, 0x61, 0x64, 0x65, 0xa2, 0x02, 0x03,
	0x54, 0x58, 0x58, 0xaa, 0x02, 0x05, 0x54, 0x72, 0x61, 0x64, 0x65, 0xca, 0x02, 0x05, 0x54, 0x72,
	0x61, 0x64, 0x65, 0xe2, 0x02, 0x11, 0x54, 0x72, 0x61, 0x64, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x05, 0x54, 0x72, 0x61, 0x64, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_define_trade_open_state_proto_rawDescOnce sync.Once
	file_define_trade_open_state_proto_rawDescData = file_define_trade_open_state_proto_rawDesc
)

func file_define_trade_open_state_proto_rawDescGZIP() []byte {
	file_define_trade_open_state_proto_rawDescOnce.Do(func() {
		file_define_trade_open_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_define_trade_open_state_proto_rawDescData)
	})
	return file_define_trade_open_state_proto_rawDescData
}

var file_define_trade_open_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_define_trade_open_state_proto_goTypes = []any{
	(OpenState)(0), // 0: trade.OpenState
}
var file_define_trade_open_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_define_trade_open_state_proto_init() }
func file_define_trade_open_state_proto_init() {
	if File_define_trade_open_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_define_trade_open_state_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_define_trade_open_state_proto_goTypes,
		DependencyIndexes: file_define_trade_open_state_proto_depIdxs,
		EnumInfos:         file_define_trade_open_state_proto_enumTypes,
	}.Build()
	File_define_trade_open_state_proto = out.File
	file_define_trade_open_state_proto_rawDesc = nil
	file_define_trade_open_state_proto_goTypes = nil
	file_define_trade_open_state_proto_depIdxs = nil
}
